language: swift
osx_image: xcode10.2

before_install:
- gem install cocoapods

script:
- pod install
- set -o pipefail && xcodebuild -workspace SegueRazer.xcworkspace -scheme SegueRazer test | xcpretty -c
